import { ContentType } from '@prisma/client'

const contentTypeMap: Record<string, ContentType> = {
  '.png': ContentType.PNG,
  '.jpg': ContentType.JPEG,
  '.jpeg': ContentType.JPEG,
  '.gif': ContentType.GIF,
  '.svg': ContentType.SVG,
  '.bmp': ContentType.BMP,
  '.tiff': ContentType.TIFF,
  '.ico': ContentType.ICO,
  '.webp': ContentType.WEBP,
  '.mp4': ContentType.MP4,
  '.webm': ContentType.WEBM,
  '.flv': ContentType.FLV,
  '.avi': ContentType.AVI,
  '.mov': ContentType.MOV,
  '.mp3': ContentType.MP3,
  '.ogg': ContentType.OGG,
  '.wav': ContentType.WAV,
  '.flac': ContentType.FLAC,
  '.aac': ContentType.AAC,
  '.wma': ContentType.WMA,
  '.zip': ContentType.ZIP,
  '.tar': ContentType.TAR,
  '.gz': ContentType.GZ,
  '.bz2': ContentType.BZ2,
  '.rar': ContentType.RAR,
  '.pdf': ContentType.PDF,
  '.doc': ContentType.DOC,
  '.docx': ContentType.DOCX,
  '.xls': ContentType.XLS,
  '.xlsx': ContentType.XLSX,
  '.ppt': ContentType.PPT,
  '.pptx': ContentType.PPTX,
  '.md': ContentType.MARKDOWN,
  '.html': ContentType.HTML,
  '.js': ContentType.JAVASCRIPT,
  '.jsx': ContentType.JAVASCRIPTREACT,
  '.ts': ContentType.TYPESCRIPT,
  '.tsx': ContentType.TYPESCRIPTREACT,
  '.css': ContentType.CSS,
  '.less': ContentType.LESS,
  '.sass': ContentType.SASS,
  '.scss': ContentType.SCSS,
  '.json': ContentType.JSON,
  '.jsonc': ContentType.JSONC,
  '.yaml': ContentType.YAML,
  '.yml': ContentType.YAML,
  '.toml': ContentType.TOML,
  '.xml': ContentType.XML,
  '.sql': ContentType.SQL,
  '.bash': ContentType.BASH,
  '.sh': ContentType.BASH,
  '.ps1': ContentType.POWERSHELL,
  '.bat': ContentType.BATCH,
  '.c': ContentType.C,
  '.cpp': ContentType.CPP,
  '.diff': ContentType.DIFF,
  '.java': ContentType.JAVA,
  '.py': ContentType.PYTHON,
  '.rb': ContentType.RUBY,
  '.go': ContentType.GO,
  '.rs': ContentType.RUST,
  '.swift': ContentType.SWIFT,
  '.kt': ContentType.KOTLIN,
  '.php': ContentType.PHP,
  '.lua': ContentType.LUA,
  '.erl': ContentType.ERLANG,
  '.cs': ContentType.CSHARP,
  '.vb': ContentType.VB,
  '.coffee': ContentType.COFFEESCRIPT,
  '.dart': ContentType.DART,
  '.matlab': ContentType.MATLAB,
  '.lisp': ContentType.LISP,
  '.nginx': ContentType.NGINX,
  '.prisma': ContentType.PRISMA,
}

export function guessContentType(inputName: string): ContentType {
  const ext = inputName.slice(inputName.lastIndexOf('.')).toLowerCase()
  return contentTypeMap[ext] || ContentType.OTHER
}
