'use client'

export { default as SvgDial01 } from './assets/dial-01.svg?icon'
export { default as SvgDial02 } from './assets/dial-02.svg?icon'
export { default as SvgDial03 } from './assets/dial-03.svg?icon'
export { default as SvgDial04 } from './assets/dial-04.svg?icon'
export { default as SvgDial05 } from './assets/dial-05.svg?icon'
export { default as SvgDial06 } from './assets/dial-06.svg?icon'
export { default as SvgDial07 } from './assets/dial-07.svg?icon'
export { default as SvgDial08 } from './assets/dial-08.svg?icon'
export { default as SvgDial09 } from './assets/dial-09.svg?icon'
export { default as SvgDial10 } from './assets/dial-10.svg?icon'
export { default as SvgDial11 } from './assets/dial-11.svg?icon'
export { default as SvgDial12 } from './assets/dial-12.svg?icon'
export { default as SvgDial13 } from './assets/dial-13.svg?icon'
export { default as SvgError } from './assets/error.svg?icon'
export { default as SvgGithub } from './assets/github.svg?icon'
export { default as SvgGoogle } from './assets/google.svg?icon'
export { default as SvgLoading } from './assets/loading.svg?icon'
export { default as SvgSuccess } from './assets/success.svg?icon'
