export { default as SvgError } from './assets/error.svg'
export { default as SvgGithub } from './assets/github.svg'
export { default as SvgGoogle } from './assets/google.svg'
export { default as SvgLoading } from './assets/loading.svg'
export { default as SvgSuccess } from './assets/success.svg'
