export { default as SvgError } from './assets/error.svg?icon'
export { default as SvgGithub } from './assets/github.svg?icon'
export { default as SvgGoogle } from './assets/google.svg?icon'
export { default as SvgLoading } from './assets/loading.svg?icon'
export { default as SvgSuccess } from './assets/success.svg?icon'
