# 需要额外建一个 test.yml

name: test
on:
  push:
    branches:
      - feat/ci
  pull_request:
    branches:
      - feat/ci
  workflow_call:

env:
  # https://stackoverflow.com/a/75486166
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: 'centos:7'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.29.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm test
